root: true
extends: eslint:recommended
parserOptions:
  ecmaVersion: 2018
env:
  node: true
  es6: true
rules:
  no-console: 2
  curly: 2
  indent: 
    - error
    - 2
  quotes:
    - error
    - single
